# vnet-7 stretched-homed DC2 — subnet 172.16.156.0/24 (client-9-dc2-sh).
apiVersion: services.eda.nokia.com/v2
kind: VirtualNetwork
metadata:
  name: vnet-7
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/dci: sh-dc2
spec:
  bridgeDomains:
    - name: bd-7
      spec:
        encapOptions:
          vxlan:
            tunnelIndexPool: tunnel-index-pool
            vniPool: vni-pool
        eviPool: evi-pool
        macLearning:
          agingTimeSeconds: 300
          enabled: true
        macLimit: 2000
        type: EVPNVXLAN
  bridgeInterfaces: []
  irbInterfaces:
    - name: irb-7
      spec:
        bridgeDomain: bd-7
        ipAddresses:
          - ipv4Address:
              ipPrefix: 172.16.156.254/24
              primary: true
        ipMTU: 1500
        ipv4:
          arpTimeoutSeconds: 14400
          learnUnsolicitedARP: Disabled
        router: router-7
  routedInterfaces: []
  routers:
    - name: router-7
      spec:
        bgp:
          autonomousSystem: 65407
          ebgpPreference: 170
          enabled: true
          ibgpPreference: 170
          ipv4Unicast:
            enabled: true
          minWaitToAdvertiseSeconds: 0
          rapidWithdrawl: true
          waitForFIBInstall: false
        encapOptions:
          vxlan:
            tunnelIndexPool: tunnel-index-pool
            vniPool: vni-pool
        eviPool: evi-pool
        routerID: 7.7.7.7
        type: EVPNVXLAN
  vlans:
    - name: vlan-null-vnet-7
      spec:
        bridgeDomain: bd-7
        interfaceSelectors:
          - eda.nokia.com/vnet-7=vlan-bd-7
        vlanID: "null"
