# WAN ISLs — option 2 (IS-IS + SR-MPLS). OSPF disabled so apply replaces option 1.
# X1b PE side uses user CR isis-instance-backbone (Fabric does not emit a PE instance).
apiVersion: fabrics.eda.nokia.com/v1
kind: ISL
metadata:
  name: dcgw-1-to-dcgw-2
  namespace: clab-srl-leaf-spine-dcgw
spec:
  localDefaultRouter: router-dcgw-1
  localInterface: dcgw-1-ethernet-1-3
  ospf:
    enabled: false
  isis:
    enabled: true
    addressFamilies:
      - IPv4
    localInstance: isis-instance-1
    remoteInstance: isis-instance-1
  poolIPv4: ipv4-pool
  remoteDefaultRouter: router-dcgw-2
  remoteInterface: dcgw-2-ethernet-1-3
---
apiVersion: fabrics.eda.nokia.com/v1
kind: ISL
metadata:
  name: dcgw-1-to-pe-1
  namespace: clab-srl-leaf-spine-dcgw
spec:
  localDefaultRouter: router-sros-pe-1
  localInterface: sros-pe-1-ethernet-1-1-1
  ospf:
    enabled: false
  isis:
    enabled: true
    addressFamilies:
      - IPv4
    localInstance: isis-instance-backbone
    remoteInstance: isis-instance-1
  poolIPv4: ipv4-pool
  remoteDefaultRouter: router-dcgw-1
  remoteInterface: dcgw-1-ethernet-1-5
---
apiVersion: fabrics.eda.nokia.com/v1
kind: ISL
metadata:
  name: dcgw-2-pe-1
  namespace: clab-srl-leaf-spine-dcgw
spec:
  localDefaultRouter: router-sros-pe-1
  localInterface: sros-pe-1-ethernet-1-a-2-1
  ospf:
    enabled: false
  isis:
    enabled: true
    addressFamilies:
      - IPv4
    localInstance: isis-instance-backbone
    remoteInstance: isis-instance-1
  poolIPv4: ipv4-pool
  remoteDefaultRouter: router-dcgw-2
  remoteInterface: dcgw-2-ethernet-1-5
---
apiVersion: fabrics.eda.nokia.com/v1
kind: ISL
metadata:
  name: dcgw-3-to-dcgw-4
  namespace: clab-srl-leaf-spine-dcgw
spec:
  localDefaultRouter: router-dcgw-3
  localInterface: dcgw-3-ethernet-1-3
  ospf:
    enabled: false
  isis:
    enabled: true
    addressFamilies:
      - IPv4
    localInstance: isis-instance-2
    remoteInstance: isis-instance-2
  poolIPv4: ipv4-pool
  remoteDefaultRouter: router-dcgw-4
  remoteInterface: dcgw-4-ethernet-1-3
---
apiVersion: fabrics.eda.nokia.com/v1
kind: ISL
metadata:
  name: dcgw-3-to-pe-2
  namespace: clab-srl-leaf-spine-dcgw
spec:
  localDefaultRouter: router-sros-pe-2
  localInterface: sros-pe-2-ethernet-1-a-3-1
  ospf:
    enabled: false
  isis:
    enabled: true
    addressFamilies:
      - IPv4
    localInstance: isis-instance-backbone
    remoteInstance: isis-instance-2
  poolIPv4: ipv4-pool
  remoteDefaultRouter: router-dcgw-3
  remoteInterface: dcgw-3-ethernet-1-6
---
apiVersion: fabrics.eda.nokia.com/v1
kind: ISL
metadata:
  name: dcgw-4-to-pe-2
  namespace: clab-srl-leaf-spine-dcgw
spec:
  localDefaultRouter: router-sros-pe-2
  localInterface: sros-pe-2-ethernet-1-a-4-1
  ospf:
    enabled: false
  isis:
    enabled: true
    addressFamilies:
      - IPv4
    localInstance: isis-instance-backbone
    remoteInstance: isis-instance-2
  poolIPv4: ipv4-pool
  remoteDefaultRouter: router-dcgw-4
  remoteInterface: dcgw-4-ethernet-1-6
---
