# WAN import DC1: VPNv4 stitch RT 101 only. No remote EVPN (no remote fabric VTEPs).
apiVersion: routingpolicies.eda.nokia.com/v1
kind: Policy
metadata:
  name: import-dci-services-dc-1
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/dci: underlay-isolation-draft
spec:
  defaultAction:
    policyResult: Reject
  statements:
    - name: reject-dc1-soo-evpn
      action:
        policyResult: Reject
      match:
        families:
          - EVPN
        bgp:
          communitySet: soo-1122
    - name: reject-all-remote-evpn
      action:
        policyResult: Reject
      match:
        families:
          - EVPN
    - name: accept-remote-hub-ipvpn
      action:
        policyResult: Accept
        tags:
          applyTagSet: tag-10
      match:
        protocol: BGP_IPVPN
        bgp:
          communitySet: dci-rt-dc2-l3
