# Hub (vnet-2) interconnect import: both DC1 spoke stitch RTs.
apiVersion: routingpolicies.eda.nokia.com/v1
kind: CommunitySet
metadata:
  name: dci-rt-hub-spoke-import
  namespace: clab-srl-leaf-spine-dcgw
spec:
  members:
    - target:1:100
    - target:1:105
