# Hub RIC importPolicy: accept spoke stitch RTs 100 (vnet-1) and 102 (vnet-5).
apiVersion: routingpolicies.eda.nokia.com/v1
kind: CommunitySet
metadata:
  name: vpn-import-rts
  namespace: clab-srl-leaf-spine-dcgw
spec:
  members:
    - target:1:100
    - target:1:102
