# MH L3-DCI DC1b — client-12, leaf-1 + leaf-2, VLAN 200, 10.200.1.0/24.
apiVersion: services.eda.nokia.com/v2
kind: VirtualNetwork
metadata:
  name: vnet-mh-l3-dc1b
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/mh: l3-dc1b
spec:
  bridgeDomains:
    - name: bd-mh-200-dc1b
      spec:
        encapOptions:
          vxlan:
            tunnelIndexPool: tunnel-index-pool
            vniPool: vni-pool
        eviPool: evi-pool
        macLearning:
          agingTimeSeconds: 300
          enabled: true
        macLimit: 2000
        type: EVPNVXLAN
  bridgeInterfaces: []
  irbInterfaces:
    - name: irb-mh-200-dc1b
      spec:
        bridgeDomain: bd-mh-200-dc1b
        ipAddresses:
          - ipv4Address:
              ipPrefix: 10.200.1.254/24
              primary: true
        ipMTU: 1500
        ipv4:
          arpTimeoutSeconds: 14400
          learnUnsolicitedARP: Disabled
        router: router-mh-dc1b
  routedInterfaces: []
  routers:
    - name: router-mh-dc1b
      spec:
        bgp:
          autonomousSystem: 65200
          ebgpPreference: 170
          enabled: true
          ibgpPreference: 170
          ipv4Unicast:
            enabled: true
          minWaitToAdvertiseSeconds: 0
          rapidWithdrawl: true
          waitForFIBInstall: false
        encapOptions:
          vxlan:
            tunnelIndexPool: tunnel-index-pool
            vniPool: vni-pool
        eviPool: evi-pool
        routerID: 8.8.8.9
        type: EVPNVXLAN
  vlans:
    - name: vlan-200-mh-dc1b
      spec:
        bridgeDomain: bd-mh-200-dc1b
        interfaceSelectors:
          - eda.nokia.com/vnet-mh-l3-dc1b=vlan-bd-mh-200-dc1b
        vlanID: "200"
