# MH L3-DCI DC2b — client-13, leaf-7 + leaf-8, VLAN 200, 10.200.2.0/24.
apiVersion: services.eda.nokia.com/v2
kind: VirtualNetwork
metadata:
  name: vnet-mh-l3-dc2b
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/mh: l3-dc2b
spec:
  bridgeDomains:
    - name: bd-mh-200-dc2b
      spec:
        encapOptions:
          vxlan:
            tunnelIndexPool: tunnel-index-pool
            vniPool: vni-pool
        eviPool: evi-pool
        macLearning:
          agingTimeSeconds: 300
          enabled: true
        macLimit: 2000
        type: EVPNVXLAN
  bridgeInterfaces: []
  irbInterfaces:
    - name: irb-mh-200-dc2b
      spec:
        bridgeDomain: bd-mh-200-dc2b
        ipAddresses:
          - ipv4Address:
              ipPrefix: 10.200.2.254/24
              primary: true
        ipMTU: 1500
        ipv4:
          arpTimeoutSeconds: 14400
          learnUnsolicitedARP: Disabled
        router: router-mh-dc2b
  routedInterfaces: []
  routers:
    - name: router-mh-dc2b
      spec:
        bgp:
          autonomousSystem: 65201
          ebgpPreference: 170
          enabled: true
          ibgpPreference: 170
          ipv4Unicast:
            enabled: true
          minWaitToAdvertiseSeconds: 0
          rapidWithdrawl: true
          waitForFIBInstall: false
        encapOptions:
          vxlan:
            tunnelIndexPool: tunnel-index-pool
            vniPool: vni-pool
        eviPool: evi-pool
        routerID: 9.9.9.10
        type: EVPNVXLAN
  vlans:
    - name: vlan-200-mh-dc2b
      spec:
        bridgeDomain: bd-mh-200-dc2b
        interfaceSelectors:
          - eda.nokia.com/vnet-mh-l3-dc2b=vlan-bd-mh-200-dc2b
        vlanID: "200"
