# L3 native DC1 edges for vnet-1 — operational Talos 2026-08-24:
# client-1 on leaf-1 e1-5, client-2 on leaf-2 e1-6 (not leaf-4).
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: srl-leaf-1-ethernet-1-5
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/role: edge
    eda.nokia.com/vnet-1: vlan-bd-1
spec:
  description: edge L3 vnet-1 DC1 — client-1
  enabled: true
  encapType: "Null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-5
      lacpPortPriority: 32768
      node: srl-leaf-1
  type: Interface
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: srl-leaf-2-ethernet-1-6
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/role: edge
    eda.nokia.com/vnet-1: vlan-bd-1
spec:
  description: edge L3 vnet-1 DC1 — client-2
  enabled: true
  encapType: "Null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-6
      lacpPortPriority: 32768
      node: srl-leaf-2
  type: Interface
