# L3 native DC1 edges for vnet-1 — client-1 (leaf-1), client-2 (leaf-4).
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: srl-leaf-1-ethernet-1-5
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/role: edge
    eda.nokia.com/vnet-1: vlan-bd-1
spec:
  description: edge L3 vnet-1 DC1 — client-1-vnet-1-dc1
  enabled: true
  encapType: "Null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-5
      lacpPortPriority: 32768
      node: srl-leaf-1
  type: Interface
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: srl-leaf-4-ethernet-1-5
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/role: edge
    eda.nokia.com/vnet-1: vlan-bd-1
spec:
  description: edge L3 vnet-1 DC1 — client-2-vnet-1-dc1
  enabled: true
  encapType: "Null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-5
      lacpPortPriority: 32768
      node: srl-leaf-4
  type: Interface
