# vnet-5 interconnect export: stitch RT 105 (SRL: 1 EVPN route-type per statement).
apiVersion: routingpolicies.eda.nokia.com/v1
kind: Policy
metadata:
  name: export-dci-stitch-vnet-5
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/dci: l3-stitch
spec:
  defaultAction:
    policyResult: Reject
  statements:
    - name: export-local-evpn-type-1
      action:
        policyResult: Accept
      match:
        families:
          - EVPN
        bgp:
          communitySet: dci-rt-vnet-5-stitch
          evpnRouteTypes:
            - 1
    - name: export-local-evpn-type-2
      action:
        policyResult: Accept
      match:
        families:
          - EVPN
        bgp:
          communitySet: dci-rt-vnet-5-stitch
          evpnRouteTypes:
            - 2
    - name: export-local-evpn-type-3
      action:
        policyResult: Accept
      match:
        families:
          - EVPN
        bgp:
          communitySet: dci-rt-vnet-5-stitch
          evpnRouteTypes:
            - 3
    - name: export-local-evpn-type-4
      action:
        policyResult: Accept
      match:
        families:
          - EVPN
        bgp:
          communitySet: dci-rt-vnet-5-stitch
          evpnRouteTypes:
            - 4
    - name: export-local-evpn-type-5
      action:
        policyResult: Accept
      match:
        families:
          - EVPN
        bgp:
          communitySet: dci-rt-vnet-5-stitch
          evpnRouteTypes:
            - 5
    - name: export-local-ipvpn-stitch
      action:
        policyResult: Accept
      match:
        protocol: BGP_IPVPN
        bgp:
          communitySet: dci-rt-vnet-5-stitch
