# WAN import on DC2 DCI BGP peers: accept spoke VPNv4 RT 100 (vnet-1) and RT 105 (vnet-5).
apiVersion: routingpolicies.eda.nokia.com/v1
kind: Policy
metadata:
  name: import-dci-services-dc-2
  namespace: clab-srl-leaf-spine-dcgw
  labels:
    eda.nokia.com/dci: vpnv4-wan-l3
spec:
  defaultAction:
    policyResult: Reject
  statements:
    - name: reject-dc2-soo-evpn
      action:
        policyResult: Reject
      match:
        families:
          - EVPN
        bgp:
          communitySet: soo-2211
    - name: accept-remote-l2-type-2-evpn
      action:
        policyResult: Accept
        tags:
          applyTagSet: tag-20
      match:
        families:
          - EVPN
        bgp:
          communitySet: dci-rt-l2-import-dc2
          evpnRouteTypes:
            - 2
    - name: accept-remote-l2-type-3-evpn
      action:
        policyResult: Accept
        tags:
          applyTagSet: tag-20
      match:
        families:
          - EVPN
        bgp:
          communitySet: dci-rt-l2-import-dc2
          evpnRouteTypes:
            - 3
    - name: reject-all-remote-evpn
      action:
        policyResult: Reject
      match:
        families:
          - EVPN
    - name: accept-remote-spoke-ipvpn-vnet-1
      action:
        policyResult: Accept
      match:
        bgp:
          communitySet: dci-rt-dc1-l3
    - name: accept-remote-spoke-ipvpn-vnet-5
      action:
        policyResult: Accept
      match:
        bgp:
          communitySet: dci-rt-vnet-5-stitch
